### PR TITLE
Initial 0.8 port

### PR DESCRIPTION
**Pull request by atotic**
Not working due to gapi errors. 0.5 component has the same error.
this.accessToken = e.detail.result.access_token;

### CODE REVIEW

**Comment by ebidel** [comment]
@jeffposnick can you take a look?

**Comment by jeffposnick** [comment]
Using the `gapi.auth2` library to authenticate with YouTube-related scopes isn't viable right now, due to the +Page issue brought up in https://github.com/GoogleWebComponents/google-youtube-upload/pull/5 (and tracked via an internal bug as well).

I can do a review and exercise the code while logging in as a real Google Account, but I don't think we can consider this element ready for general consumption until it depends on a version of `<google-signin>` that allows you to auth as a +Page.

**Comment by atotic** [comment]
I was not aware of gapi.auth2 problem. But demo does work on my local machine, using my atotic@gmail.com account.

**Comment by jeffposnick** [comment]
The ported code all seems to work well when I try it with a non +Page YouTube account, so :+1: in general to this PR, and thanks! The changes that need to be made to support +Page accounts are in the backend of Google Signin 2.0, so I doubt anything will need to change in this PR before it's merged.

But like I said, I'm hesitant to make much noise about this element (e.g., via the YouTube API social channels) until it gets fixed.

**Comment by atotic** [comment]
I am fixing this element for 0.9, new changes coming in soon

**Comment by atotic** [comment]
Works

**Comment by jeffposnick** [comment]
:+1:

**Comment by addyosmani** [comment]
LGTM2

**Comment by ebidel** [comment]
LGTM @jeffposnick you get the final say.

**Pull request merged**
