### PR TITLE
Updating for the `0.3.0` version of the google-signin component.

### PR DESCRIPTION
**Pull request by Zoramite**
Separated out the clientid from from the upload element.

### CODE REVIEW

**Comment by jeffposnick** [comment]
Thanks for taking this on!

Could you bump up the `bower.json` version to "1.0.1"?

I'm trying this out locally and can't complete the OAuth 2 flow. I get the following error:

`The JavaScript origin in the request: storagerelay://http/localhost:8000?id=auth560693 did not match a registered JavaScript origin.`

How were you able to test this out? I believe that the OAuth 2 registration that we're using for this demo is owned by @ebidel so maybe there's something he needs to do in the Google Cloud console to whitelist the special `storagerelay` JavaScript origin.

**Comment by Zoramite** [comment]
Hi @jeffposnick. The `clientId` used on the demo page is tied to the googlewebcomponents.github.io domain and shouldn't add localhost in for security. In order to test it locally you need to create your own project at console.developers.google.com and add the localhost origin then update the `clientId` in the `demo.html` page.

I tested the signin portion of this locally and it was working. I was getting some other errors when I actually tried to upload a test video, but I thought it was an issue with my console configuration.

**Comment by jeffposnick** [comment]
I had thought that the `clientId` was associated with a registration that had `http://localhost` registered as a valid JavaScript origin to facilitate testing, but I'm mistaken. Sorry! I've swapped out the `clientId` for one I've previously used for testing.

@Zoramite, I'm seeing some errors logged to `console` while testing out `demo.html` using the new element, and things don't appear functional. I'll follow up with you with those logs directly as I don't know if there's any sensitive account information included.

**Comment by jeffposnick** [comment]
We've traced the errors back to going through the OAuth 2 flow using a Google+ Page.

This is an [important use case](http://youtube-eng.blogspot.com/2013/06/google-page-identities-and-youtube-api_24.html) for the YouTube APIs, and we need to hold off on this PR until the new flow works with Google+ Pages.

**Comment by addyosmani** [comment]
I assume this change is no longer required as of https://github.com/GoogleWebComponents/google-youtube-upload/pull/7 etc, right?

**Comment by jeffposnick** [comment]
Yes, this is obsolete. Closing.

**Pull request closed without merging**
